// Mocks generated by Mockito 5.4.6 from annotations
// in codivium_notes_app/test/features/settings/domain/usecases/toggle_theme_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:codivium_notes_app/features/settings/domain/entities/app_settings.dart'
    as _i5;
import 'package:codivium_notes_app/features/settings/domain/repositories/settings_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<Exception, _i5.AppSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i4.Future<_i2.Either<Exception, _i5.AppSettings>>.value(
                  _FakeEither_0<Exception, _i5.AppSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<Exception, _i5.AppSettings>>);

  @override
  _i4.Future<_i2.Either<Exception, void>> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i4.Future<_i2.Either<Exception, void>>.value(
              _FakeEither_0<Exception, void>(
                this,
                Invocation.method(#toggleTheme, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<Exception, void>>);

  @override
  _i4.Future<_i2.Either<Exception, void>> changeFont(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#changeFont, [fontFamily]),
            returnValue: _i4.Future<_i2.Either<Exception, void>>.value(
              _FakeEither_0<Exception, void>(
                this,
                Invocation.method(#changeFont, [fontFamily]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<Exception, void>>);
}
