// Mocks generated by Mockito 5.4.6 from annotations
// in codivium_notes_app/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:codivium_notes_app/core/database/database_helper.dart' as _i5;
import 'package:codivium_notes_app/features/calendar/data/datasources/calendar_local_datasource.dart'
    as _i14;
import 'package:codivium_notes_app/features/calendar/domain/repositories/calendar_repository.dart'
    as _i13;
import 'package:codivium_notes_app/features/notes/data/datasources/notes_local_datasource.dart'
    as _i9;
import 'package:codivium_notes_app/features/notes/data/models/note_model.dart'
    as _i4;
import 'package:codivium_notes_app/features/notes/data/models/todo_model.dart'
    as _i10;
import 'package:codivium_notes_app/features/notes/domain/entities/note.dart'
    as _i8;
import 'package:codivium_notes_app/features/notes/domain/repositories/notes_repository.dart'
    as _i7;
import 'package:codivium_notes_app/features/search/data/datasources/search_local_datasource.dart'
    as _i12;
import 'package:codivium_notes_app/features/search/domain/repositories/search_repository.dart'
    as _i11;
import 'package:codivium_notes_app/features/settings/data/datasources/settings_local_datasource.dart'
    as _i17;
import 'package:codivium_notes_app/features/settings/domain/entities/app_settings.dart'
    as _i16;
import 'package:codivium_notes_app/features/settings/domain/repositories/settings_repository.dart'
    as _i15;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNoteModel_2 extends _i1.SmartFake implements _i4.NoteModel {
  _FakeNoteModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i5.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NotesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRepository extends _i1.Mock implements _i7.NotesRepository {
  MockNotesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<Exception, List<_i8.Note>>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue:
                _i6.Future<_i3.Either<Exception, List<_i8.Note>>>.value(
                  _FakeEither_1<Exception, List<_i8.Note>>(
                    this,
                    Invocation.method(#getAllNotes, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, List<_i8.Note>>>);

  @override
  _i6.Future<_i3.Either<Exception, _i8.Note>> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i6.Future<_i3.Either<Exception, _i8.Note>>.value(
              _FakeEither_1<Exception, _i8.Note>(
                this,
                Invocation.method(#getNoteById, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, _i8.Note>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> createNote(_i8.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#createNote, [note]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> updateNote(_i8.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#updateNote, [note]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#deleteNote, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#toggleFavorite, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);

  @override
  _i6.Future<_i3.Either<Exception, List<_i8.Note>>> sortByImportance() =>
      (super.noSuchMethod(
            Invocation.method(#sortByImportance, []),
            returnValue:
                _i6.Future<_i3.Either<Exception, List<_i8.Note>>>.value(
                  _FakeEither_1<Exception, List<_i8.Note>>(
                    this,
                    Invocation.method(#sortByImportance, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, List<_i8.Note>>>);
}

/// A class which mocks [NotesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDatasource extends _i1.Mock
    implements _i9.NotesLocalDatasource {
  MockNotesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.NoteModel>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i6.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i6.Future<List<_i4.NoteModel>>);

  @override
  _i6.Future<_i4.NoteModel> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i6.Future<_i4.NoteModel>.value(
              _FakeNoteModel_2(this, Invocation.method(#getNoteById, [id])),
            ),
          )
          as _i6.Future<_i4.NoteModel>);

  @override
  _i6.Future<void> createNote(_i4.NoteModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateNote(_i4.NoteModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.NoteModel>> sortByImportance() =>
      (super.noSuchMethod(
            Invocation.method(#sortByImportance, []),
            returnValue: _i6.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i6.Future<List<_i4.NoteModel>>);

  @override
  _i6.Future<List<_i10.TodoModel>> getTodosForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosForNote, [noteId]),
            returnValue: _i6.Future<List<_i10.TodoModel>>.value(
              <_i10.TodoModel>[],
            ),
          )
          as _i6.Future<List<_i10.TodoModel>>);

  @override
  _i6.Future<void> insertTodo(_i10.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#insertTodo, [todo]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTodo(_i10.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTodo(String? todoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [todoId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i11.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<Exception, List<_i8.Note>>> searchNotes(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue:
                _i6.Future<_i3.Either<Exception, List<_i8.Note>>>.value(
                  _FakeEither_1<Exception, List<_i8.Note>>(
                    this,
                    Invocation.method(#searchNotes, [query]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, List<_i8.Note>>>);
}

/// A class which mocks [SearchLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocalDatasource extends _i1.Mock
    implements _i12.SearchLocalDatasource {
  MockSearchLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.NoteModel>> searchNotes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue: _i6.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i6.Future<List<_i4.NoteModel>>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i13.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<Exception, List<_i8.Note>>> getNotesByDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDate, [date]),
            returnValue:
                _i6.Future<_i3.Either<Exception, List<_i8.Note>>>.value(
                  _FakeEither_1<Exception, List<_i8.Note>>(
                    this,
                    Invocation.method(#getNotesByDate, [date]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, List<_i8.Note>>>);

  @override
  _i6.Future<_i3.Either<Exception, List<_i8.Note>>> getNotesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDateRange, [start, end]),
            returnValue:
                _i6.Future<_i3.Either<Exception, List<_i8.Note>>>.value(
                  _FakeEither_1<Exception, List<_i8.Note>>(
                    this,
                    Invocation.method(#getNotesByDateRange, [start, end]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, List<_i8.Note>>>);
}

/// A class which mocks [CalendarLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarLocalDatasource extends _i1.Mock
    implements _i14.CalendarLocalDatasource {
  MockCalendarLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.NoteModel>> getNotesByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDate, [date]),
            returnValue: _i6.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i6.Future<List<_i4.NoteModel>>);

  @override
  _i6.Future<List<_i4.NoteModel>> getNotesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDateRange, [start, end]),
            returnValue: _i6.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i6.Future<List<_i4.NoteModel>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i15.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<Exception, _i16.AppSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i6.Future<_i3.Either<Exception, _i16.AppSettings>>.value(
                  _FakeEither_1<Exception, _i16.AppSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<Exception, _i16.AppSettings>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#toggleTheme, []),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);

  @override
  _i6.Future<_i3.Either<Exception, void>> changeFont(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#changeFont, [fontFamily]),
            returnValue: _i6.Future<_i3.Either<Exception, void>>.value(
              _FakeEither_1<Exception, void>(
                this,
                Invocation.method(#changeFont, [fontFamily]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<Exception, void>>);
}

/// A class which mocks [SettingsLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDatasource extends _i1.Mock
    implements _i17.SettingsLocalDatasource {
  MockSettingsLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> getIsDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#getIsDarkMode, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> setIsDarkMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setIsDarkMode, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> getFontFamily() =>
      (super.noSuchMethod(
            Invocation.method(#getFontFamily, []),
            returnValue: _i6.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#getFontFamily, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> setFontFamily(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#setFontFamily, [fontFamily]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
