// Mocks generated by Mockito 5.4.6 from annotations
// in codivium_notes_app/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:codivium_notes_app/core/database/database_helper.dart' as _i12;
import 'package:codivium_notes_app/features/calendar/data/datasources/calendar_local_datasource.dart'
    as _i26;
import 'package:codivium_notes_app/features/calendar/domain/repositories/calendar_repository.dart'
    as _i8;
import 'package:codivium_notes_app/features/calendar/domain/usecases/get_notes_by_date.dart'
    as _i27;
import 'package:codivium_notes_app/features/notes/data/datasources/notes_local_datasource.dart'
    as _i14;
import 'package:codivium_notes_app/features/notes/data/models/note_model.dart'
    as _i5;
import 'package:codivium_notes_app/features/notes/data/models/todo_model.dart'
    as _i15;
import 'package:codivium_notes_app/features/notes/domain/entities/note.dart'
    as _i13;
import 'package:codivium_notes_app/features/notes/domain/repositories/notes_repository.dart'
    as _i6;
import 'package:codivium_notes_app/features/notes/domain/usecases/create_note.dart'
    as _i18;
import 'package:codivium_notes_app/features/notes/domain/usecases/delete_note.dart'
    as _i20;
import 'package:codivium_notes_app/features/notes/domain/usecases/get_all_notes.dart'
    as _i16;
import 'package:codivium_notes_app/features/notes/domain/usecases/get_note_by_id.dart'
    as _i17;
import 'package:codivium_notes_app/features/notes/domain/usecases/share_note.dart'
    as _i23;
import 'package:codivium_notes_app/features/notes/domain/usecases/sort_notes_by_importance.dart'
    as _i22;
import 'package:codivium_notes_app/features/notes/domain/usecases/toggle_favorite.dart'
    as _i21;
import 'package:codivium_notes_app/features/notes/domain/usecases/update_note.dart'
    as _i19;
import 'package:codivium_notes_app/features/search/data/datasources/search_local_datasource.dart'
    as _i24;
import 'package:codivium_notes_app/features/search/domain/repositories/search_repository.dart'
    as _i7;
import 'package:codivium_notes_app/features/search/domain/usecases/search_notes.dart'
    as _i25;
import 'package:codivium_notes_app/features/settings/data/datasources/settings_local_datasource.dart'
    as _i29;
import 'package:codivium_notes_app/features/settings/domain/entities/app_settings.dart'
    as _i28;
import 'package:codivium_notes_app/features/settings/domain/repositories/settings_repository.dart'
    as _i9;
import 'package:codivium_notes_app/features/settings/domain/usecases/change_font.dart'
    as _i31;
import 'package:codivium_notes_app/features/settings/domain/usecases/toggle_theme.dart'
    as _i30;
import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:sqflite_common/sql.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCursor_2 extends _i1.SmartFake implements _i2.QueryCursor {
  _FakeQueryCursor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_3 extends _i1.SmartFake implements _i2.Batch {
  _FakeBatch_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_4<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNoteModel_5 extends _i1.SmartFake implements _i5.NoteModel {
  _FakeNoteModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotesRepository_6 extends _i1.SmartFake
    implements _i6.NotesRepository {
  _FakeNotesRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchRepository_7 extends _i1.SmartFake
    implements _i7.SearchRepository {
  _FakeSearchRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarRepository_8 extends _i1.SmartFake
    implements _i8.CalendarRepository {
  _FakeCalendarRepository_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsRepository_9 extends _i1.SmartFake
    implements _i9.SettingsRepository {
  _FakeSettingsRepository_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  _i2.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.Database);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<T> transaction<T>(
    _i3.Future<T> Function(_i2.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action], {#exclusive: exclusive}),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> readTransaction<T>(
    _i3.Future<T> Function(_i2.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readTransaction, [action]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> devInvokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeMethod, [method, arguments]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawInsert, [sql, arguments]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i11.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [table, values],
              {
                #nullColumnHack: nullColumnHack,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i3.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<_i2.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
            returnValue: _i3.Future<_i2.QueryCursor>.value(
              _FakeQueryCursor_2(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.QueryCursor>);

  @override
  _i3.Future<_i2.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
            returnValue: _i3.Future<_i2.QueryCursor>.value(
              _FakeQueryCursor_2(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.QueryCursor>);

  @override
  _i3.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i11.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, values],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i2.Batch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeBatch_3(this, Invocation.method(#batch, [])),
          )
          as _i2.Batch);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i12.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i3.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i3.Future<_i2.Database>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NotesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRepository extends _i1.Mock implements _i6.NotesRepository {
  MockNotesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#getAllNotes, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);

  @override
  _i3.Future<_i4.Either<Exception, _i13.Note>> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, _i13.Note>>.value(
              _FakeEither_4<Exception, _i13.Note>(
                this,
                Invocation.method(#getNoteById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i13.Note>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> createNote(_i13.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#createNote, [note]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> updateNote(_i13.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#updateNote, [note]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#deleteNote, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#toggleFavorite, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> sortByImportance() =>
      (super.noSuchMethod(
            Invocation.method(#sortByImportance, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#sortByImportance, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [NotesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDatasource extends _i1.Mock
    implements _i14.NotesLocalDatasource {
  MockNotesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.NoteModel>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i3.Future<List<_i5.NoteModel>>.value(
              <_i5.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i5.NoteModel>>);

  @override
  _i3.Future<_i5.NoteModel> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i3.Future<_i5.NoteModel>.value(
              _FakeNoteModel_5(this, Invocation.method(#getNoteById, [id])),
            ),
          )
          as _i3.Future<_i5.NoteModel>);

  @override
  _i3.Future<void> createNote(_i5.NoteModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateNote(_i5.NoteModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.NoteModel>> sortByImportance() =>
      (super.noSuchMethod(
            Invocation.method(#sortByImportance, []),
            returnValue: _i3.Future<List<_i5.NoteModel>>.value(
              <_i5.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i5.NoteModel>>);

  @override
  _i3.Future<List<_i15.TodoModel>> getTodosForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodosForNote, [noteId]),
            returnValue: _i3.Future<List<_i15.TodoModel>>.value(
              <_i15.TodoModel>[],
            ),
          )
          as _i3.Future<List<_i15.TodoModel>>);

  @override
  _i3.Future<void> insertTodo(_i15.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#insertTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTodo(_i15.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTodo(String? todoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [todoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GetAllNotes].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllNotes extends _i1.Mock implements _i16.GetAllNotes {
  MockGetAllNotes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [GetNoteById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNoteById extends _i1.Mock implements _i17.GetNoteById {
  MockGetNoteById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, _i13.Note>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, _i13.Note>>.value(
              _FakeEither_4<Exception, _i13.Note>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i13.Note>>);
}

/// A class which mocks [CreateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNote extends _i1.Mock implements _i18.CreateNote {
  MockCreateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call(_i13.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#call, [note]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, [note]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [UpdateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNote extends _i1.Mock implements _i19.UpdateNote {
  MockUpdateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call(_i13.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#call, [note]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, [note]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [DeleteNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNote extends _i1.Mock implements _i20.DeleteNote {
  MockDeleteNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [ToggleFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleFavorite extends _i1.Mock implements _i21.ToggleFavorite {
  MockToggleFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [SortNotesByImportance].
///
/// See the documentation for Mockito's code generation for more information.
class MockSortNotesByImportance extends _i1.Mock
    implements _i22.SortNotesByImportance {
  MockSortNotesByImportance() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.NotesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotesRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.NotesRepository);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [ShareNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareNote extends _i1.Mock implements _i23.ShareNote {
  MockShareNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({required String? title, required String? content}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#title: title, #content: content}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i7.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> searchNotes(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#searchNotes, [query]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [SearchLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocalDatasource extends _i1.Mock
    implements _i24.SearchLocalDatasource {
  MockSearchLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.NoteModel>> searchNotes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue: _i3.Future<List<_i5.NoteModel>>.value(
              <_i5.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i5.NoteModel>>);
}

/// A class which mocks [SearchNotes].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchNotes extends _i1.Mock implements _i25.SearchNotes {
  MockSearchNotes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.SearchRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSearchRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.SearchRepository);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> call(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#call, [query]),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#call, [query]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i8.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> getNotesByDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDate, [date]),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#getNotesByDate, [date]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> getNotesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDateRange, [start, end]),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#getNotesByDateRange, [start, end]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [CalendarLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarLocalDatasource extends _i1.Mock
    implements _i26.CalendarLocalDatasource {
  MockCalendarLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.NoteModel>> getNotesByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDate, [date]),
            returnValue: _i3.Future<List<_i5.NoteModel>>.value(
              <_i5.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i5.NoteModel>>);

  @override
  _i3.Future<List<_i5.NoteModel>> getNotesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByDateRange, [start, end]),
            returnValue: _i3.Future<List<_i5.NoteModel>>.value(
              <_i5.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i5.NoteModel>>);
}

/// A class which mocks [GetNotesByDate].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotesByDate extends _i1.Mock implements _i27.GetNotesByDate {
  MockGetNotesByDate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.CalendarRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCalendarRepository_8(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.CalendarRepository);

  @override
  _i3.Future<_i4.Either<Exception, List<_i13.Note>>> call(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#call, [date]),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i13.Note>>>.value(
                  _FakeEither_4<Exception, List<_i13.Note>>(
                    this,
                    Invocation.method(#call, [date]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i13.Note>>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i9.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, _i28.AppSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, _i28.AppSettings>>.value(
                  _FakeEither_4<Exception, _i28.AppSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, _i28.AppSettings>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#toggleTheme, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> changeFont(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#changeFont, [fontFamily]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#changeFont, [fontFamily]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [SettingsLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDatasource extends _i1.Mock
    implements _i29.SettingsLocalDatasource {
  MockSettingsLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> getIsDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#getIsDarkMode, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setIsDarkMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setIsDarkMode, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getFontFamily() =>
      (super.noSuchMethod(
            Invocation.method(#getFontFamily, []),
            returnValue: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getFontFamily, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> setFontFamily(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#setFontFamily, [fontFamily]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ToggleTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleTheme extends _i1.Mock implements _i30.ToggleTheme {
  MockToggleTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_9(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.SettingsRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [ChangeFont].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeFont extends _i1.Mock implements _i31.ChangeFont {
  MockChangeFont() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_9(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.SettingsRepository);

  @override
  _i3.Future<_i4.Either<Exception, void>> call(String? fontFamily) =>
      (super.noSuchMethod(
            Invocation.method(#call, [fontFamily]),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _FakeEither_4<Exception, void>(
                this,
                Invocation.method(#call, [fontFamily]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}
